image: rc2s/rc2s-ci:v0.3

pipelines:
  default:
    - step:
        script:
          - echo "It's RC2S !"
          - gradle --gradle-user-home=/home/user/ clean publishToMavenLocal compileTestJava -PskipServerAutodeploy=true -PskipJNLPAutodeploy=true